#!/bin/bash

# set path so we can find puppet
export PATH=/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin

# run puppet verbosely, with good exit codes
puppet apply \
  --debug \
  --verbose \
  --detailed-exitcodes \
  $@
status=$?

# exit code of 0 or 2 means success in puppet
(( $status == 0 || $status == 2 ))
